import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    /**
     * [aapt2 website](https://developer.android.com/studio) */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * [apdu4j website](https://github.com/martinpaljak/apdu4j) */
    const val apdu4j: String = "com.github.martinpaljak:apdu4j:" + Versions.apdu4j

    /**
     * [bcpg-jdk15on website](http://www.bouncycastle.org/java.html) */
    const val bcpg_jdk15on: String = "org.bouncycastle:bcpg-jdk15on:" + Versions.bcpg_jdk15on

    /**
     * [bcprov-jdk15on website](http://www.bouncycastle.org/java.html) */
    const val bcprov_jdk15on: String = "org.bouncycastle:bcprov-jdk15on:" + Versions.bcprov_jdk15on

    const val com_afollestad_material_dialogs_core: String =
            "com.afollestad.material-dialogs:core:" + Versions.com_afollestad_material_dialogs_core

    /**
     * [appcompat-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val com_android_support_appcompat_v7: String =
            "com.android.support:appcompat-v7:" + Versions.com_android_support_appcompat_v7

    /**
     * [runner website](https://developer.android.com/testing) */
    const val com_android_support_test_runner: String =
            "com.android.support.test:runner:" + Versions.com_android_support_test_runner

    const val com_github_ben_manes_versions_gradle_plugin: String =
            "com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:" + Versions.com_github_ben_manes_versions_gradle_plugin

    const val com_gradle_build_scan_gradle_plugin: String =
            "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" + Versions.com_gradle_build_scan_gradle_plugin

    const val com_jfrog_artifactory_gradle_plugin: String =
            "com.jfrog.artifactory:com.jfrog.artifactory.gradle.plugin:" + Versions.com_jfrog_artifactory_gradle_plugin

    /**
     * [constraint-layout website](http://tools.android.com) */
    const val constraint_layout: String =
            "com.android.support.constraint:constraint-layout:" + Versions.constraint_layout

    const val crashlytics: String =
            "com.crashlytics.sdk.android:crashlytics:" + Versions.crashlytics

    /**
     * [design website](http://developer.android.com/tools/extras/support-library.html) */
    const val design: String = "com.android.support:design:" + Versions.design

    /**
     * [dexcount-gradle-plugin website](http://github.com/KeepSafe/dexcount-gradle-plugin/) */
    const val dexcount_gradle_plugin: String =
            "com.getkeepsafe.dexcount:dexcount-gradle-plugin:" + Versions.dexcount_gradle_plugin

    /**
     * [espresso-core website](https://developer.android.com/testing) */
    const val espresso_core: String =
            "com.android.support.test.espresso:espresso-core:" + Versions.espresso_core

    /**
     * [gradle-git website](https://github.com/ajoberstar/gradle-git) */
    const val gradle_git: String = "org.ajoberstar:gradle-git:" + Versions.gradle_git

    /**
     * [guava website](https://github.com/google/guava) */
    const val guava: String = "com.google.guava:guava:" + Versions.guava

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val io_fabric_tools_gradle: String =
            "com.android.tools.build:gradle:" + Versions.io_fabric_tools_gradle

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [jnasmartcardio website](https://github.com/jnasmartcardio/jnasmartcardio) */
    const val jnasmartcardio: String =
            "io.github.jnasmartcardio:jnasmartcardio:" + Versions.jnasmartcardio

    /**
     * [jopt-simple website](http://jopt-simple.github.io/jopt-simple) */
    const val jopt_simple: String = "net.sf.jopt-simple:jopt-simple:" + Versions.jopt_simple

    /**
     * [json-simple website](http://code.google.com/p/json-simple/) */
    const val json_simple: String = "com.googlecode.json-simple:json-simple:" + Versions.json_simple

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * [kotlin-android-extensions website](https://kotlinlang.org/) */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.kotlin_android_extensions

    /**
     * [kotlin-coroutines-retrofit website](https://github.com/gildor/kotlin-coroutines-retrofit) */
    const val kotlin_coroutines_retrofit: String =
            "ru.gildor.coroutines:kotlin-coroutines-retrofit:" + Versions.kotlin_coroutines_retrofit

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.kotlin_gradle_plugin

    /**
     * [kotlin-stdlib-jdk7 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk7: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" + Versions.kotlin_stdlib_jdk7

    /**
     * [kotlintest website](http://www.github.com/kotlintest/kotlintest) */
    const val kotlintest: String = "io.kotlintest:kotlintest:" + Versions.kotlintest

    /**
     * [kotlinx-coroutines-android website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" + Versions.kotlinx_coroutines_android

    /**
     * [lint-gradle website](https://developer.android.com/studio) */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    const val multidex: String = "com.android.support:multidex:" + Versions.multidex

    const val multidex_instrumentation: String =
            "com.android.support:multidex-instrumentation:" + Versions.multidex_instrumentation

    const val nordpol_android: String = "com.fidesmo:nordpol-android:" + Versions.nordpol_android

    /**
     * [play-publisher website](https://github.com/Triple-T/gradle-play-publisher) */
    const val play_publisher: String =
            "com.github.triplet.gradle:play-publisher:" + Versions.play_publisher

    /**
     * [timber website](https://github.com/JakeWharton/timber) */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber
}
