import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Versions {
    const val aapt2: String = "3.2.0-4818971" // available: milestone=3.3.0-alpha13-5013011

    const val apdu4j: String = "1.0-SNAPSHOT" // available: milestone=18.10.04

    const val bcpg_jdk15on: String = "1.56" // available: milestone=1.60

    const val bcprov_jdk15on: String = "1.58" // available: milestone=1.60

    const val com_afollestad_material_dialogs_core: String =
            "0.9.6.0" // available: milestone=2.0.0-beta4

    const val com_android_support_appcompat_v7: String = "28.0.0" // up-to-date

    const val com_android_support_test_runner: String = "1.0.2" // up-to-date

    const val com_github_ben_manes_versions_gradle_plugin: String = "0.20.0" // up-to-date

    const val com_gradle_build_scan_gradle_plugin: String = "1.15.1" // available: milestone=2.0

    const val com_jfrog_artifactory_gradle_plugin: String = "4.7.5" // available: milestone=4.8.1

    const val constraint_layout: String = "1.1.3" // available: milestone=2.0.0-alpha2

    const val crashlytics: String = "2.9.4" // available: milestone=2.9.5

    const val design: String = "27.0.1" // available: milestone=28.0.0

    const val dexcount_gradle_plugin: String = "0.8.3" // available: milestone=0.8.4

    const val espresso_core: String = "3.0.2" // up-to-date

    const val gradle_git: String = "0.2.3" // available: milestone=1.7.2

    const val guava: String = "18.0" // available: milestone=26.0-jre

    const val io_fabric_tools_gradle: String = "3.2.1" // available: milestone=3.3.0-alpha13

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "0.2.3" // available: milestone=0.2.4

    const val jnasmartcardio: String = "0.2.7" // up-to-date

    const val jopt_simple: String = "5.0.4" // available: milestone=6.0-alpha-3

    const val json_simple: String = "1.1.1" // up-to-date

    const val junit: String = "4.12" // up-to-date

    const val kotlin_android_extensions: String = "1.2.71" // up-to-date

    const val kotlin_coroutines_retrofit: String = "0.11.0" // available: milestone=0.13.0

    const val kotlin_gradle_plugin: String = "1.2.71" // up-to-date

    const val kotlin_stdlib_jdk7: String = "1.2.61" // available: milestone=1.2.71

    const val kotlintest: String = "2.0.7" // up-to-date

    const val kotlinx_coroutines_android: String = "0.23.4" // available: milestone=0.30.2

    const val lint_gradle: String = "26.2.0" // available: milestone=26.3.0-alpha13

    const val multidex: String = "1.0.3" // up-to-date

    const val multidex_instrumentation: String = "1.0.2" // available: milestone=1.0.3

    const val nordpol_android: String = "0.1.23" // up-to-date

    const val play_publisher: String = "1.2.2" // available: milestone=2.0.0-beta1

    const val timber: String = "4.7.1" // up-to-date

    object Gradle {
        const val runningVersion: String = "4.10.2"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.1-20181016235832+0000"

        const val releaseCandidate: String = ""
    }
}
